version: '3'
services:
  app:
    build: .
    ports:
      - "8501:8501"
      - "8000:8000"
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    volumes:
      - ./data:/app/data
      - ./embeddings/generated:/app/embeddings/generated
      - ./vector_store/faiss_index:/app/vector_store/faiss_index